import type { Experience } from "@/types";

export const EXPERIENCES: Experience[] = [
  {
    id: "exp-1",
    role: "Senior Software Engineer",
    company: "TESARK Technologies",
    period: "Aug 2026 — Present",
    location: "Chennai, Tamil Nadu",
    description: [
      "Own end-to-end architecture and delivery of multi-tenant SaaS platforms, driving technical direction across frontend, backend, and cloud layers.",
      "Lead design of scalable event-driven systems with BullMQ, Redis, and audit-ready data flows for production reliability.",
      "Mentor engineers, raise code quality through reviews, and align delivery with product and business goals.",
      "Drive AI-powered features — MCP servers, agent workflows, RAG pipelines, and LLM integrations — from prototype to production.",
      "Establish engineering standards for API security, CI/CD, and AWS operations.",
    ],
    technologies: [
      "Next.js",
      "NestJS",
      "PostgreSQL",
      "Redis",
      "AWS",
      "Docker",
      "BullMQ",
      "TypeORM",
      "MCP",
      "LLM",
      "RAG",
      "LangChain",
      "LangGraph",
    ],
  },
  {
    id: "exp-2",
    role: "Associate Software Engineer III",
    company: "TESARK Technologies",
    period: "Aug 2022 — Jul 2026",
    location: "Chennai, Tamil Nadu",
    description: [
      "Built and shipped multi-tenant SaaS features with schema-per-tenant PostgreSQL, JWT auth, RBAC, and session management.",
      "Implemented event-driven backends with BullMQ queues, Redis caching, and comprehensive activity logging.",
      "Designed REST APIs with Swagger/OpenAPI documentation and production-grade error handling.",
      "Contributed to AI integrations, real-time features, and cloud deployments on AWS with Docker and CI/CD.",
      "Progressed from hands-on feature delivery to owning larger modules ahead of promotion to Senior Software Engineer.",
    ],
    technologies: [
      "Next.js",
      "NestJS",
      "PostgreSQL",
      "Redis",
      "AWS",
      "Docker",
      "BullMQ",
      "TypeORM",
    ],
  },
  {
    id: "exp-3",
    role: "Trainee Engineer",
    company: "TESARK Technologies",
    period: "May 2022 — Jul 2022",
    location: "Chennai, Tamil Nadu",
    description: [
      "Completed structured training in full-stack development covering frontend, backend, and database fundamentals.",
      "Built and contributed to internal projects using React, Node.js, and REST APIs under senior engineer guidance.",
      "Learned engineering best practices including code reviews, Git workflows, and agile delivery processes.",
      "Gained hands-on experience with TypeScript, API integration, and responsive UI implementation.",
    ],
    technologies: [
      "React",
      "Node.js",
      "JavaScript",
      "TypeScript",
      "REST APIs",
      "Git",
    ],
  },
];

export const EXPERIENCE_TIMELINE = EXPERIENCES.map((exp) => ({
  name: exp.company,
  role: exp.role,
  period: exp.period,
  value: exp.id === "exp-1" ? 100 : exp.id === "exp-2" ? 75 : 40,
}));
